"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 11:15:57.587341
"""

from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backup_policies",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("cron_schedule", sa.String(length=64), nullable=False),
        sa.Column(
            "backup_type",
            sa.Enum("full", "incremental", name="backup_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("worm_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "worm_mode",
            sa.Enum("none", "enterprise", "compliance", name="worm_mode", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "NOT worm_enabled OR worm_mode <> 'none'", name=op.f("ck_backup_policies_worm_mode_set")
        ),
        sa.CheckConstraint("retention_days > 0", name=op.f("ck_backup_policies_retention_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_policies")),
        sa.UniqueConstraint("name", name=op.f("uq_backup_policies_name")),
    )
    op.create_table(
        "backup_targets",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("management_port", sa.Integer(), nullable=False),
        sa.Column("credentials_encrypted", sa.Text(), nullable=False),
        sa.Column(
            "model",
            sa.Enum("x3000", "x6000", "x8000", "x9000", name="appliance_model", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("serial_number", sa.String(length=64), nullable=True),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column(
            "health_status",
            sa.Enum(
                "unknown", "healthy", "degraded", "fault", name="health_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("firmware_version", sa.String(length=64), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_targets")),
        sa.UniqueConstraint("device_id", name=op.f("uq_backup_targets_device_id")),
        sa.UniqueConstraint("name", name=op.f("uq_backup_targets_name")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_backup_targets_serial_number")),
    )
    op.create_table(
        "alarm_records",
        sa.Column("backup_target_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("critical", "major", "warning", name="alarm_severity", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("raised_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_by", sa.String(length=128), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ack_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backup_target_id"],
            ["backup_targets.id"],
            name=op.f("fk_alarm_records_backup_target_id_backup_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alarm_records")),
        sa.UniqueConstraint("backup_target_id", "sequence", "event_id", name="uq_alarm_identity"),
    )
    op.create_index("ix_alarm_active", "alarm_records", ["backup_target_id", "cleared_at"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("resource_name", sa.String(length=128), nullable=True),
        sa.Column("backup_target_id", sa.Uuid(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("success", "failure", name="audit_outcome", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backup_target_id"],
            ["backup_targets.id"],
            name=op.f("fk_audit_logs_backup_target_id_backup_targets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor"), "audit_logs", ["actor"], unique=False)
    op.create_index(op.f("ix_audit_logs_backup_target_id"), "audit_logs", ["backup_target_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_occurred_at"), "audit_logs", ["occurred_at"], unique=False)
    op.create_table(
        "capacity_metrics",
        sa.Column("backup_target_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_capacity_gb", sa.Float(), nullable=False),
        sa.Column("used_physical_gb", sa.Float(), nullable=False),
        sa.Column("logic_written_gb", sa.Float(), nullable=False),
        sa.Column("post_dedup_gb", sa.Float(), nullable=False),
        sa.Column("dedup_ratio", sa.Float(), nullable=False),
        sa.Column("compression_ratio", sa.Float(), nullable=False),
        sa.Column("reduction_ratio", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backup_target_id"],
            ["backup_targets.id"],
            name=op.f("fk_capacity_metrics_backup_target_id_backup_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capacity_metrics")),
    )
    op.create_index(
        "ix_capacity_target_time", "capacity_metrics", ["backup_target_id", "timestamp"], unique=False
    )
    op.create_table(
        "hardware_snapshots",
        sa.Column("backup_target_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "overall_status",
            sa.Enum("ok", "degraded", "fault", name="hardware_health", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("max_cpu_percent", sa.Float(), nullable=False),
        sa.Column("max_memory_percent", sa.Float(), nullable=False),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column("summary", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backup_target_id"],
            ["backup_targets.id"],
            name=op.f("fk_hardware_snapshots_backup_target_id_backup_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hardware_snapshots")),
    )
    op.create_index(
        "ix_hardware_target_time", "hardware_snapshots", ["backup_target_id", "timestamp"], unique=False
    )
    op.create_table(
        "protected_assets",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum(
                "vmware", "database", "file_share", "lun", name="asset_type", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("backup_target_id", sa.Uuid(), nullable=False),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backup_target_id"],
            ["backup_targets.id"],
            name=op.f("fk_protected_assets_backup_target_id_backup_targets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["backup_policies.id"],
            name=op.f("fk_protected_assets_policy_id_backup_policies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protected_assets")),
        sa.UniqueConstraint("backup_target_id", "name", name="uq_asset_target_name"),
    )
    op.create_index(
        op.f("ix_protected_assets_backup_target_id"), "protected_assets", ["backup_target_id"], unique=False
    )
    op.create_table(
        "throughput_samples",
        sa.Column("backup_target_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("write_throughput_mb_s", sa.Float(), nullable=False),
        sa.Column("read_throughput_mb_s", sa.Float(), nullable=False),
        sa.Column("iops", sa.Integer(), nullable=False),
        sa.Column("active_streams", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backup_target_id"],
            ["backup_targets.id"],
            name=op.f("fk_throughput_samples_backup_target_id_backup_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_throughput_samples")),
    )
    op.create_index(
        "ix_throughput_target_time", "throughput_samples", ["backup_target_id", "timestamp"], unique=False
    )
    op.create_table(
        "backup_jobs",
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("backup_target_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("asset_name", sa.String(length=255), nullable=True),
        sa.Column("policy_id", sa.Uuid(), nullable=True),
        sa.Column(
            "backup_type",
            sa.Enum("full", "incremental", name="backup_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "PARTIALLY_SUCCESSFUL",
                "CANCELLED",
                name="job_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_transferred_gb", sa.Float(), nullable=False),
        sa.Column("throughput_mb_s", sa.Float(), nullable=False),
        sa.Column("log_messages", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint("data_transferred_gb >= 0", name=op.f("ck_backup_jobs_transferred_non_negative")),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["protected_assets.id"],
            name=op.f("fk_backup_jobs_asset_id_protected_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["backup_target_id"],
            ["backup_targets.id"],
            name=op.f("fk_backup_jobs_backup_target_id_backup_targets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["backup_policies.id"],
            name=op.f("fk_backup_jobs_policy_id_backup_policies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_jobs")),
        sa.UniqueConstraint("backup_target_id", "task_id", name="uq_job_target_task"),
    )
    op.create_index(op.f("ix_backup_jobs_asset_id"), "backup_jobs", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_backup_jobs_backup_target_id"), "backup_jobs", ["backup_target_id"], unique=False
    )
    op.create_index(op.f("ix_backup_jobs_status"), "backup_jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backup_jobs_status"), table_name="backup_jobs")
    op.drop_index(op.f("ix_backup_jobs_backup_target_id"), table_name="backup_jobs")
    op.drop_index(op.f("ix_backup_jobs_asset_id"), table_name="backup_jobs")
    op.drop_table("backup_jobs")
    op.drop_index("ix_throughput_target_time", table_name="throughput_samples")
    op.drop_table("throughput_samples")
    op.drop_index(op.f("ix_protected_assets_backup_target_id"), table_name="protected_assets")
    op.drop_table("protected_assets")
    op.drop_index("ix_hardware_target_time", table_name="hardware_snapshots")
    op.drop_table("hardware_snapshots")
    op.drop_index("ix_capacity_target_time", table_name="capacity_metrics")
    op.drop_table("capacity_metrics")
    op.drop_index(op.f("ix_audit_logs_occurred_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_backup_target_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_alarm_active", table_name="alarm_records")
    op.drop_table("alarm_records")
    op.drop_table("backup_targets")
    op.drop_table("backup_policies")
    # ### end Alembic commands ###
