"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 09:39:44.814703
"""

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_devices",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("management_port", sa.Integer(), nullable=False),
        sa.Column("credentials_encrypted", sa.Text(), nullable=False),
        sa.Column(
            "model",
            sa.Enum("dorado_v7", "oceanprotect", name="device_model", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column(
            "health_status",
            sa.Enum(
                "unknown", "healthy", "degraded", "fault", name="health_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("firmware_version", sa.String(length=64), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_devices")),
        sa.UniqueConstraint("device_id", name=op.f("uq_storage_devices_device_id")),
        sa.UniqueConstraint("name", name=op.f("uq_storage_devices_name")),
    )
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("quota_block_gb", sa.Integer(), nullable=False),
        sa.Column("quota_file_gb", sa.Integer(), nullable=False),
        sa.Column("quota_object_gb", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "quota_block_gb >= 0 AND quota_file_gb >= 0 AND quota_object_gb >= 0",
            name=op.f("ck_tenants_quotas_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("name", name=op.f("uq_tenants_name")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("resource_name", sa.String(length=128), nullable=True),
        sa.Column("storage_device_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("success", "failure", name="audit_outcome", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["storage_device_id"],
            ["storage_devices.id"],
            name=op.f("fk_audit_logs_storage_device_id_storage_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_audit_logs_tenant_id_tenants"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor"), "audit_logs", ["actor"], unique=False)
    op.create_index(op.f("ix_audit_logs_occurred_at"), "audit_logs", ["occurred_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_storage_device_id"), "audit_logs", ["storage_device_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_table(
        "object_buckets",
        sa.Column("bucket_name", sa.String(length=63), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("quota_gb", sa.Integer(), nullable=True),
        sa.Column("s3_endpoint", sa.String(length=255), nullable=False),
        sa.Column("storage_device_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["storage_device_id"],
            ["storage_devices.id"],
            name=op.f("fk_object_buckets_storage_device_id_storage_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_object_buckets_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_buckets")),
        sa.UniqueConstraint("bucket_name", name=op.f("uq_object_buckets_bucket_name")),
    )
    op.create_index(
        op.f("ix_object_buckets_storage_device_id"), "object_buckets", ["storage_device_id"], unique=False
    )
    op.create_index(op.f("ix_object_buckets_tenant_id"), "object_buckets", ["tenant_id"], unique=False)
    op.create_table(
        "protection_policies",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column(
            "worm_mode",
            sa.Enum("none", "enterprise", "compliance", name="worm_mode", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("snapshot_schedule", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint("retention_days > 0", name=op.f("ck_protection_policies_retention_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_protection_policies_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protection_policies")),
        sa.UniqueConstraint("name", name=op.f("uq_protection_policies_name")),
    )
    op.create_index(
        op.f("ix_protection_policies_tenant_id"), "protection_policies", ["tenant_id"], unique=False
    )
    op.create_table(
        "filesystems",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("size_gb", sa.Integer(), nullable=False),
        sa.Column(
            "protocol",
            sa.Enum("nfs", "cifs", name="file_protocol", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("share_path", sa.String(length=255), nullable=True),
        sa.Column("quota_hard_gb", sa.Integer(), nullable=True),
        sa.Column("quota_soft_gb", sa.Integer(), nullable=True),
        sa.Column(
            "quota_status",
            sa.Enum(
                "none",
                "within_limit",
                "soft_exceeded",
                "hard_exceeded",
                name="quota_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("array_fs_id", sa.String(length=32), nullable=True),
        sa.Column("storage_device_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("protection_policy_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint("size_gb > 0", name=op.f("ck_filesystems_size_positive")),
        sa.ForeignKeyConstraint(
            ["protection_policy_id"],
            ["protection_policies.id"],
            name=op.f("fk_filesystems_protection_policy_id_protection_policies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["storage_device_id"],
            ["storage_devices.id"],
            name=op.f("fk_filesystems_storage_device_id_storage_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_filesystems_tenant_id_tenants"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filesystems")),
        sa.UniqueConstraint("storage_device_id", "array_fs_id", name="uq_filesystem_array_fs"),
    )
    op.create_index(
        op.f("ix_filesystems_storage_device_id"), "filesystems", ["storage_device_id"], unique=False
    )
    op.create_index(op.f("ix_filesystems_tenant_id"), "filesystems", ["tenant_id"], unique=False)
    op.create_table(
        "storage_volumes",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("wwn", sa.String(length=64), nullable=True),
        sa.Column("size_gb", sa.Integer(), nullable=False),
        sa.Column(
            "provisioning",
            sa.Enum("thin", "thick", name="provisioning", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "mapping_status",
            sa.Enum("unmapped", "mapped", name="mapping_status", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("array_lun_id", sa.String(length=32), nullable=True),
        sa.Column("storage_device_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("protection_policy_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint("size_gb > 0", name=op.f("ck_storage_volumes_size_positive")),
        sa.ForeignKeyConstraint(
            ["protection_policy_id"],
            ["protection_policies.id"],
            name=op.f("fk_storage_volumes_protection_policy_id_protection_policies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["storage_device_id"],
            ["storage_devices.id"],
            name=op.f("fk_storage_volumes_storage_device_id_storage_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_storage_volumes_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_volumes")),
        sa.UniqueConstraint("storage_device_id", "array_lun_id", name="uq_volume_array_lun"),
        sa.UniqueConstraint("wwn", name=op.f("uq_storage_volumes_wwn")),
    )
    op.create_index(
        op.f("ix_storage_volumes_storage_device_id"), "storage_volumes", ["storage_device_id"], unique=False
    )
    op.create_index(op.f("ix_storage_volumes_tenant_id"), "storage_volumes", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_volumes_tenant_id"), table_name="storage_volumes")
    op.drop_index(op.f("ix_storage_volumes_storage_device_id"), table_name="storage_volumes")
    op.drop_table("storage_volumes")
    op.drop_index(op.f("ix_filesystems_tenant_id"), table_name="filesystems")
    op.drop_index(op.f("ix_filesystems_storage_device_id"), table_name="filesystems")
    op.drop_table("filesystems")
    op.drop_index(op.f("ix_protection_policies_tenant_id"), table_name="protection_policies")
    op.drop_table("protection_policies")
    op.drop_index(op.f("ix_object_buckets_tenant_id"), table_name="object_buckets")
    op.drop_index(op.f("ix_object_buckets_storage_device_id"), table_name="object_buckets")
    op.drop_table("object_buckets")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_storage_device_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_occurred_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("tenants")
    op.drop_table("storage_devices")
    # ### end Alembic commands ###
