"""asset appliance id

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 11:24:40.339940
"""

from alembic import op
import sqlalchemy as sa


revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("protected_assets", sa.Column("array_asset_id", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("protected_assets", "array_asset_id")
    # ### end Alembic commands ###
